language: clojure
lein: lein2
script: bash ./deploy.sh
cache:
  directories:
    - $HOME/.m2
jdk:
  - oraclejdk8

script:
  - bash ./build.sh

env:
  global:
    - GITHUB_REF: github.com/Aidbox/site.git
    - secure: GOj5/MgvpdmREOXM4bSECqSy+Izesc7O7N/Z7viaXutaJqxfXaT3j+2X0DNwFVipElIx5y7uvZhu4iJKWnIBI00fC4suGxGboFG5u3FvvPdd9gBzGW0smuLAfhbaOm1buMh8W0mcQV0dVebB9mwpXX3uz5Gz8/LxzdbdO5dvbucig5qURY0L2UMQjOsZ/1py0cTrGBgjHH5S7nafL5lIYWU/f1Epv1CyjqKarB328Qcc0AJ8pPj1xpYNA7M7SUE3FLbtgOZXnAwZ+mgjrMb5dRhJcLD5Dg4kIAnJ+Cl1Tyw7qfhHq8zoW//uy4te5A6KITorRJxsVPS3vzfnZn8TXICa72jnsOEKMYRxC/CW/9KtYkWvlE5qh0HsHsMMeKb88EVJZPENXnx+CUd67KGwrjUZG5VHqzX2S5uOGbVWkju/Iud0fWJhxVmnNzDcXddIvgXllYeChi/L4glRccNKpaDU/FSvk9PVmVudT6HKk5JMv+oKER/+imAImsytjOHBLkQgSsWzbgJQtPFPbCxHQ6txKF8MUFTn1EE9e9ROvwLD1Kt4ZxFUnWVyLt/vGQ41Q/NtvLw90UiFjDpg6myzd0rhUEt7rsMwxIbO6o0l7CTtwGBNYkpJjxBEONRCwJl3yKMcCZrq0oCL0Y1w5QEDPCORuePaZl8TaOwdVkpU1j4=
